-- Automatically write a pair closing symbol for any opening
return {}
-- return {
-- 	"nvim-mini/mini.pairs",
-- 	event = "VeryLazy",
-- 	opts = {
-- 		modes = { insert = true, command = true, terminal = false },
-- 		skip_next = [=[[%w%%%'%[%"%.%`%$]]=],
-- 		skip_ts = { "string" },
-- 		skip_unbalanced = true,
-- 		markdown = true,
-- 	},
-- }
